version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: 'sampler-app-api'
phases:
    install:
        runtime-versions:
            dotnet: 2.2
        commands:
            - cd src/sampler-api
            - dotnet tool install -g Amazon.Lambda.Tools
    build:
        commands:
            - dotnet lambda deploy-serverless -cfg aws-lambda-tools-default.json

artifacts:
    files:
        - '**/*'
