version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: 'sampler-app-api'
phases:
    install:
        runtime-versions:
            dotnet: 2.2
        commands:
            - dotnet tool install -g Amazon.Lambda.Tools
    build:
        commands:
            - ls
            - dotnet lambda deploy-serverless --region us-east-2 -cfg src/sampler-api/aws-lambda-tools-defaults.json

artifacts:
    files:
        - '**/*'
